### ISSUE TITLE
Cannot create asset because it is a directory

### ISSUE THREAD

**Issue by leorid** [RoyTheunissen/Asset-Palette#22]
As the title says, I get this error in 2022.2.2f1

To fix, change Line 242 in "AssetPaletteCollectionEditor.cs" from

`
Directory.CreateDirectory(path);
`
To
`
Directory.CreateDirectory(Path.GetDirectoryName(path));
`

**Comment by RoyTheunissen** [comment]
Hey @leorid ! Thank you for reporting this issue, sorry for my delayed response. I'm having a hard time filtering out notifications that are truly meaningful, but I think I improved that and will be more responsive from now on.

I just merged a PR that addresses this issue. Hope it improves things for you.
